name: prototex
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - astroid=2.14.2
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - colorama=0.4.6
  - cryptography=39.0.1
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.1.55
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.1.55
  - cuda-nsight-compute=12.1.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.1.55
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.1.55
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.1.55
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.1.55
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - dill=0.3.6
  - ffmpeg=4.3
  - flake8=6.0.0
  - flit-core=3.8.0
  - freetype=2.12.1
  - gds-tools=1.6.0.25
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - isort=5.9.3
  - jpeg=9e
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.6.0.25
  - libcufile-dev=1.6.0.25
  - libcurand=10.3.2.56
  - libcurand-dev=10.3.2.56
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mccabe=0.7.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - nsight-compute=2023.1.0.15
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1t
  - pip=23.0.1
  - platformdirs=2.5.2
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pyflakes=3.0.1
  - pylint=2.16.2
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.9.16
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.1
  - tk=8.6.12
  - tomli=2.0.1
  - tomlkit=0.11.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - wheel=0.38.4
  - wrapt=1.14.1
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - async-timeout==4.0.2
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - contourpy==1.0.7
    - cycler==0.11.0
    - datasets==2.11.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - dpcpp-cpp-rt==2023.0.0
    - entrypoints==0.4
    - executing==0.8.3
    - filelock==3.6.0
    - fonttools==4.39.3
    - frozenlist==1.3.3
    - fsspec==2023.3.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - huggingface-hub==0.13.3
    - idna==3.3
    - importlib-resources==5.4.0
    - intel-cmplr-lib-rt==2023.0.0
    - intel-cmplr-lic-rt==2023.0.0
    - intel-opencl-rt==2023.0.0
    - intel-openmp==2023.0.0
    - ipykernel==6.9.2
    - ipython==8.1.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.4.4
    - llvmlite==0.39.1
    - markupsafe==2.1.1
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mkl==2023.0.0
    - mkl-fft==1.3.1
    - mkl-service==2.4.0
    - multidict==6.0.4
    - multiprocess==0.70.14
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - nbformat==5.2.0
    - nest-asyncio==1.5.4
    - notebook==6.4.10
    - numba==0.56.4
    - numpy==1.22.4
    - nvidia-htop==1.0.5
    - packaging==21.3
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.1
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.28
    - protobuf==4.22.1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==11.0.0
    - pygments==2.11.2
    - pynndescent==0.5.8
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2023.2
    - pyyaml==6.0
    - pyzmq==22.3.0
    - regex==2022.3.15
    - requests==2.27.1
    - responses==0.18.0
    - sacremoses==0.0.49
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - seaborn==0.12.2
    - send2trash==1.8.0
    - sentry-sdk==1.17.0
    - setproctitle==1.3.2
    - sklearn==0.0
    - smmap==5.0.0
    - soupsieve==2.3.1
    - stack-data==0.2.0
    - tbb==2021.8.0
    - termcolor==2.2.0
    - terminado==0.13.3
    - testpath==0.6.0
    - threadpoolctl==3.1.0
    - tokenizers==0.11.6
    - torch==1.9.0
    - torchaudio==0.9.0
    - torchvision==0.10.0
    - tornado==6.1
    - tqdm==4.63.0
    - traitlets==5.1.1
    - transformers==4.17.0
    - typing-extensions==4.5.0
    - umap==0.1.1
    - umap-learn==0.5.3
    - urllib3==1.26.15
    - wandb==0.14.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - xxhash==3.2.0
    - yarl==1.8.2
    - zipp==3.7.0
    - evaluate==0.4.0
